### ISSUE TITLE
Will you consider open source your project ?

### ISSUE THREAD

**Issue by oxarbitrage** [Loops7/cryptolib#1]
Hey, i was looking for formalization attempts of cryptography schemes in lean and i found your project to be the most complete one around. 

I will like to contribute to it by adding more schemes, fixing issues, etc so i was wondering 2 things:

1- Will you consider adding an open source licence to your project so people can contribute?
2- Will you accept pull requests ?

I am pretty new to lean and formalization is hard to me, however, i was able to find formalization code for the RSA cryptosystem in  https://github.com/aronerben/lean-rsa so i added it to your lib.

Unfortunately both projects depend in different versions of mathlib and as mathlib is unestable the API is constantly changing. Still, i was able to bump the mathlib version in `cryptolib` to the one in `rsa-lean` sacrificing one elgammal proof of semantic lemma that with some luck should not be hard to fix.

https://github.com/oxarbitrage/cryptolib/pull/1

On top of that i added the `lean-rsa` file into the lib in https://github.com/oxarbitrage/cryptolib/pull/2

Let me know what do you think and thank you for the great work you did until now.

**Comment by JoeyLupo** [comment]
Hi Alfredo, 

I went ahead and added an Apache 2.0 license to the project, so you may do what you please. For (2), I will not accept pull requests at this time, simply because I cannot guarantee that I will be able to review them in a particularly timely fashion as my time is pretty well accounted for at the moment. And further, I want to ensure that the code is still compatible with my written dissertation. Hence it might be best to just fork the project and contribute in your own repo. 

However, let me know if you have any questions as you read the work, and I'll do my best to get back to you. Thanks for the kind words and interest in this project, and I wish you the best of luck in continuing to learn about Lean and cryptography. A great resource for Lean is https://leanprover.zulipchat.com/#, where much of the community resides and is available to answer any questions that may come up.

Thanks, 
Joey

**Comment by oxarbitrage** [comment]
That is great, thank you very much for making it happen. In regards to the pull requests, yes, i can work in my own fork just wanted to make sure you are ok with it. Thanks again!
